name: publish
on: [push]
jobs:
  publish-mlgs-2024-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the MLGS Docker image
        run: |
              docker build . --tag ghcr.io/yascho/mlgs-2024-docker:latest
              docker run ghcr.io/yascho/mlgs-2024-docker:latest
              docker push ghcr.io/yascho/mlgs-2024-docker:latest
